CCFLAGS=-Wall -g

all: 1.exe 2.exe 3.exe 4.exe 5.exe 6.exe 7.exe 8.exe 9.exe

1.exe: 1.c
	gcc $(CCFLAGS) -o 1 1.c

2.exe: 2.c
	gcc $(CCFLAGS) -o 2 2.c

3.exe: 3.c
	gcc $(CCFLAGS) -o 3 3.c

4.exe: 4.c
	gcc $(CCFLAGS) -o 4 4.c

5.exe: 5.c
	gcc $(CCFLAGS) -o 5 5.c

6.exe: 6.c
	gcc $(CCFLAGS) -o 6 6.c

7.exe: 7.c
	gcc $(CCFLAGS) -o 7 7.c

8.exe: 8.c
	gcc $(CCFLAGS) -o 8 8.c

9.exe: 9.c
	gcc $(CCFLAGS) -o 9 9.c

clean:
	rm -r -f 1 2 3 4 5 6 7 8 9 1.exe 2.exe 3.exe 4.exe 5.exe 6.exe 7.exe 8.exe 9.exe